version: "3.7"

services:
  app:
    image: ghcr.io/team-india-1947/crop-disease-backend:master
    container_name: app
    depends_on:
      - db
    ports:
      - "80:8080"
    volumes:
      - /root/.aspnet/DataProtection-Keys

  db:
    image: postgres:latest
    container_name: db
    environment:
      - POSTGRES_DB=crop_db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    volumes:
      - /var/lib/postgresql/data

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 60 app --include-stopped --cleanup --include-restarting --include-stopped
