version: "3.7"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "8000:80"
    volumes:
      - /root/.aspnet/DataProtection-Keys

  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=crop_db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    volumes:
      - /var/lib/postgresql/data